name: Golang lint and run test
on:
  push:
    branches:
      - develop
    paths:
      - "**.go"
  pull_request:
    paths:
      - "**.go"
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  security-events: none

jobs:
  golint:
    name: Lint go code
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53

  gotest:
    name: Run test code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          cache: false
      - name: Test with the Go CLI
        run: go test ./v1

  msd-scan:
    name: Scan sceret and security in source code
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/security-devops-action@v1
        env:
          tools: "bandit"
          categories: "code,secrets"
          languages: "go"
  go-scan:
    name: Scan security Go Code
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: securego/gosec@master
        with:
          args: "-no-fail -fmt sarif -out results.sarif ./..."


